### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lgibson7**
Link to instructions of how to contribute a data set to Tidy Tuesday under "How to participate".

### CODE REVIEW

**Comment by lawrencelmli** [comment]
Sorry to put this on here but how do I unsubscribe from all threads
permanently? I tried to un-star the repo, stopped all GitHub notifications
and unsubscribe every week but I am still receiving these emails.

**Comment by jonthegeek** [comment]
@lawrencelmli Go to the main page of the repository (https://github.com/rfordatascience/tidytuesday) and click "unwatch" (with the eye icon). You've been unsubscribing from the individual pull request, but at some point you told GitHub to watch all activity in the entire repository.

**Review by jonthegeek — APPROVED** [review]
This is better than what's there already! We should still tweak things at some point to make it more prominent, but that will take larger editing.

**Comment by lgibson7** [comment]
Yup. I figured this would be a start. I have some ideas that I'll mention in #720.

**Pull request merged**
