### PR TITLE
Grant data for 2023 week 40.

### PR DESCRIPTION
**Pull request by jonthegeek**
And because I wanted it for R4DS!

### CODE REVIEW

**Comment by jonthegeek** [comment]
Doh, back to draft, making sure I didn't break something...

**Comment by jonthegeek** [comment]
Ok, this was fine. It's just that grants for 501c3's each only have 1 category, evidently (other things span many categories).

**Comment by tracykteal** [comment]
Looks good! In the data table, there are a few descriptions of "Are individuals eligible?" for organizations like "eligibility_nonprofits_501c3". I wasn't sure if that is correct, or should be updated to something like "Is this type of organization eligible?"

**Review by tracykteal — DISMISSED** [review]
Looks good! In the data table, there are a few descriptions of "Are individuals eligible?" for organizations like "eligibility_nonprofits_501c3". I wasn't sure if that is correct, or should be updated to something like "Is this type of organization eligible?"

**Review by tracykteal — APPROVED** [review]
All the data dictionary things look good now.

**Pull request merged**
