### PR TITLE
World's Fair data

### PR DESCRIPTION
**Pull request by jonthegeek**

### CODE REVIEW

**Review by tracykteal — APPROVED** [review]
Looks good!

**Review by lgibson7 — APPROVED** [review]
Looks good. Thanks Jon!

**Comment by lgibson7** [comment]
So the heavy lifting looks to be in the cleaning script. I'll dig into a few other weeks as well to get a better idea before tackling my own.

One suggestion I have for eliciting data set submissions is moving the request earlier in the README to the bottom of the ["How to participate section"](https://github.com/rfordatascience/tidytuesday/tree/master?tab=readme-ov-file#how-to-participate); just a short blurb directing folks to [CONTRIBUTING.md](https://github.com/rfordatascience/tidytuesday/blob/master/CONTRIBUTING.md) and [instructions.md](https://github.com/rfordatascience/tidytuesday/blob/master/data/curated/template/instructions.md). Currently ["Submitting Datasets"](https://github.com/rfordatascience/tidytuesday/tree/master?tab=readme-ov-file#submitting-datasets) is at the very bottom of the README and only mentions submitting issues rather than PRs.

**Pull request merged**
