### PR TITLE
Update tt_data_type.csv

### PR DESCRIPTION
**Pull request by thebioengineer**
resolves some issues raised in thebioengineer/tidytuesdayR#88

### CODE REVIEW

**Comment by jthomasmock** [comment]
I somehow missed this - is this still needed? Sorry!

- Tom

**Comment by thebioengineer** [comment]
The changes are still needed to exist in the file at some point. If this PR is now out of date, we can update with a new one

**Comment by jthomasmock** [comment]
Yup - sorry I missed it! if you could re-open the PR so it doesn't conflict with the existing CSV that would be ideal. 🙏

**Comment by thebioengineer** [comment]
@jthomasmock  - opened a new PR (#444) to fix this

**Comment by thebioengineer** [comment]
resolved with #444. closing this one

**Pull request closed without merging**
